
delete from tb_sys_page_cfg ;
insert into tb_sys_page_cfg values ('index/index',    '首页',     'main', 1, 1) ;
insert into tb_sys_page_cfg values ('survey/index',   '调查中心', 'main', 0, 1) ;
insert into tb_sys_page_cfg values ('brand/index',    '品牌专区', 'main', 0, 1) ;
insert into tb_sys_page_cfg values ('shop/index',     '积分商城', 'main', 0, 1) ;
insert into tb_sys_page_cfg values ('user/index',     '用户中心', 'sub',  0, 1) ;
insert into tb_sys_page_cfg values ('survey/create',  '调查创建', 'sub',  0, 1) ;
insert into tb_sys_page_cfg values ('survey/alter',   '调查修改', 'sub',  0, 1) ;
insert into tb_sys_page_cfg values ('survey/visit',   '调查访问', 'sub',  0, 1) ;
insert into tb_sys_page_cfg values ('survey/answer',  '调查参与', 'sub',  0, 1) ;
insert into tb_sys_page_cfg values ('survey/analyse', '调查分析', 'sub',  0, 1) ;
insert into tb_sys_page_cfg values ('user/visit',     '用户访问', 'sub',  0, 1) ;
insert into tb_sys_page_cfg values ('user/recover',   '密码找回', 'sub',  0, 0) ;
insert into tb_sys_page_cfg values ('search/index',   '维新搜索', 'sub',  0, 0) ;
insert into tb_sys_page_cfg values ('user/recover',   '密码找回', 'sub',  0, 0) ;

delete from tb_bas_prop_det_relation ;
insert into tb_bas_prop_det_relation values('user_type','BasUserInfo','user_type','DetUserType','user_type_code','user_type_desc') ;
insert into tb_bas_prop_det_relation values('area_province','BasUserInfo','area_province','DetAreaProvince','area_province_code','area_province_sname') ;
insert into tb_bas_prop_det_relation values('area_city','BasUserInfo','area_city','DetAreaCity','area_city_code','area_city_sname') ;
insert into tb_bas_prop_det_relation values('user_sex','BasUserInfo','user_sex','DetUserSex','user_sex_code','user_sex_desc') ;
insert into tb_bas_prop_det_relation values('user_career','BasUserInfo','user_career','DetUserCareer','user_career_code','user_career_desc') ;
insert into tb_bas_prop_det_relation values('user_edu','BasUserInfo','user_edu','DetUserEdu','user_edu_code','user_edu_desc') ;
insert into tb_bas_prop_det_relation values('user_age','BasUserInfo','user_age_section','DetUserAge','user_age_code','user_age_desc') ;
insert into tb_bas_prop_det_relation values('user_level','BasUserAccout','user_level','DetUserLevel','user_level_value','user_level_desc') ;
insert into tb_bas_prop_det_relation values('survey_type','BasSurveyInfo','survey_type','DetSurveyType','survey_type_code','survey_type_desc') ;
insert into tb_bas_prop_det_relation values('survey_class','BasSurveyInfo','survey_class','DetSurveyClass','survey_class_code','survey_class_desc') ;
insert into tb_bas_prop_det_relation values('survey_state','BasSurveyInfo','survey_state','DetSurveyState','survey_state_code','survey_state_desc') ;
insert into tb_bas_prop_det_relation values('recomm_type','BasSurveyInfo','recomm_type','DetSurveyRecommType','survey_type_code','survey_type_desc') ;

delete from tb_det_user_prop ;
insert into tb_det_user_prop values ('area_province', '省份',        'BasUserInfo','DetAreaProvince','area_province_code', 'area_province_name') ;
insert into tb_det_user_prop values ('area_city',     '城市',        'BasUserInfo','DetAreaCity','area_city_code', 'area_city_name') ;
insert into tb_det_user_prop values ('user_birthday', '生日',        'BasUserInfo','','', '') ;
insert into tb_det_user_prop values ('birth_year',    '出生年份',    'BasUserInfo','','', '') ;
insert into tb_det_user_prop values ('birth_month',   '出生月份',    'BasUserInfo','','', '') ;
insert into tb_det_user_prop values ('birth_day',     '出生日期',    'BasUserInfo','','', '') ;
insert into tb_det_user_prop values ('user_age',      '年龄',        'BasUserInfo','','', '') ;
insert into tb_det_user_prop values ('user_sex',      '性别',        'BasUserInfo','DetUserSex','user_sex_code', 'user_sex_desc') ;
insert into tb_det_user_prop values ('user_career',   '职业',        'BasUserInfo','DetUserCareer','user_career_code','user_career_desc') ;
insert into tb_det_user_prop values ('industry_class','从事行业大类','BasUserInfo','DetIndustryClass','industry_class_code','industry_class_desc' ) ;
insert into tb_det_user_prop values ('industry_sub',  '从事行业小类','BasUserInfo','DetIndustryClassSub','industry_class_sub_code','industry_class_sub_desc'   ) ;
insert into tb_det_user_prop values ('income_class',  '收入分类',    'BasUserInfo','DetUserIncome','user_income_code','user_income_desc'   ) ;
insert into tb_det_user_prop values ('income_section','收入区间',    'BasUserInfo','DetUserIncomeSection','income_section_code', 'income_section_desc' ) ;
insert into tb_det_user_prop values ('user_edu',      '教育水平',    'BasUserInfo','DetUserEdu','user_edu_code',       'user_edu_desc'       ) ;
insert into tb_det_user_prop values ('user_character','性格',        'BasUserInfo','DetUserCharacter','user_character_code', 'user_character_desc' ) ;
insert into tb_det_user_prop values ('user_affection','感情情况',    'BasUserInfo','DetUserAffection','user_affection_code', 'user_affection_desc' ) ;
insert into tb_det_user_prop values ('user_stature',  '个人身材',    'BasUserInfo','DetUserStature','user_stature_code',   'user_stature_desc'   ) ;
insert into tb_det_user_prop values ('user_hobby',    '个人爱好',    'BasUserInfo','DetUserHobby','user_hobby_code',     'user_hobby_desc'     ) ;
insert into tb_det_user_prop values ('user_desc',     '用户简介',    'BasUserInfo','','','') ;

delete from tb_det_user_type ;
insert into tb_det_user_type values(0,'无效用户') ;
insert into tb_det_user_type values(1,'官方用户') ;
insert into tb_det_user_type values(2,'付费用户') ;
insert into tb_det_user_type values(3,'认证用户') ;
insert into tb_det_user_type values(4,'高级用户') ;
insert into tb_det_user_type values(5,'普通用户') ;

delete from tb_det_area_province ;
insert into tb_det_area_province values(1, '北京市',          1002,'华北地区',  '北京') ;
insert into tb_det_area_province values(2, '天津市',          1002,'华北地区',  '天津') ;
insert into tb_det_area_province values(3, '上海市',          1003,'华东地区',  '上海') ;
insert into tb_det_area_province values(4, '重庆市',          1006,'西南地区',  '重庆') ;
insert into tb_det_area_province values(5, '河北省',          1002,'华北地区',  '河北') ;
insert into tb_det_area_province values(6, '山西省',          1002,'华北地区',  '河南') ;
insert into tb_det_area_province values(7, '台湾省',          1003,'华东地区',  '云南') ;
insert into tb_det_area_province values(8, '辽宁省',          1001,'东北地区',  '辽宁') ;
insert into tb_det_area_province values(9, '吉林省',          1001,'东北地区',  '吉林') ;
insert into tb_det_area_province values(10,'黑龙江省',        1001,'东北地区',  '黑龙江') ;
insert into tb_det_area_province values(11,'江苏省',          1003,'华东地区',  '江苏') ;
insert into tb_det_area_province values(12,'浙江省',          1003,'华东地区',  '浙江') ;
insert into tb_det_area_province values(13,'安徽省',          1003,'华东地区',  '安徽') ;
insert into tb_det_area_province values(14,'福建省',          1003,'华东地区',  '福建') ;
insert into tb_det_area_province values(15,'江西省',          1003,'华东地区',  '江西') ;
insert into tb_det_area_province values(16,'山东省',          1003,'华东地区',  '山东') ;
insert into tb_det_area_province values(17,'河南省',          1004,'华中地区',  '河南') ;
insert into tb_det_area_province values(18,'湖北省',          1004,'华中地区',  '湖北') ;
insert into tb_det_area_province values(19,'湖南省',          1004,'华中地区',  '湖南') ;
insert into tb_det_area_province values(20,'广东省',          1005,'华南地区',  '广东') ;
insert into tb_det_area_province values(21,'甘肃省',          1007,'西北地区',  '甘肃') ;
insert into tb_det_area_province values(22,'四川省',          1006,'西南地区',  '四川') ;
insert into tb_det_area_province values(23,'贵州省',          1006,'西南地区',  '贵州') ;
insert into tb_det_area_province values(24,'海南省',          1005,'华南地区',  '海南') ;
insert into tb_det_area_province values(25,'云南省',          1006,'西南地区',  '云南') ;
insert into tb_det_area_province values(26,'青海省',          1007,'西北地区',  '青海') ;
insert into tb_det_area_province values(27,'陕西省',          1007,'西北地区',  '陕西') ;
insert into tb_det_area_province values(28,'广西壮族自治区',  1005,'华南地区',  '广西') ;
insert into tb_det_area_province values(29,'西藏自治区',      1006,'西南地区',  '西藏') ;
insert into tb_det_area_province values(30,'宁夏回族自治区',  1007,'西北地区',  '宁夏') ;
insert into tb_det_area_province values(31,'新疆维吾尔自治区',1007,'西北地区',  '新疆') ;
insert into tb_det_area_province values(32,'内蒙古自治区',    1002,'华北地区',  '内蒙古') ;
insert into tb_det_area_province values(33,'香港特别行政区',  1008,'港澳台地区','香港') ;
insert into tb_det_area_province values(34,'澳门特别行政区',  1008,'港澳台地区','澳门') ;
insert into tb_det_area_province values(35,'中华台北',        1008,'港澳台地区','台湾') ;
insert into tb_det_area_province values(36,'南海诸岛',        1005,'华南地区',  '南海诸岛') ;

delete from tb_det_user_sex ;
insert into tb_det_user_sex values(1,'男') ;
insert into tb_det_user_sex values(2,'女') ;

delete from tb_det_user_career ;
insert into tb_det_user_career values(1001,'待业') ;
insert into tb_det_user_career values(1002,'退休') ;
insert into tb_det_user_career values(1003,'家庭主妇') ;
insert into tb_det_user_career values(1004,'在校学生') ;
insert into tb_det_user_career values(1005,'蓝领职工') ;
insert into tb_det_user_career values(1006,'现役军人') ;
insert into tb_det_user_career values(1007,'教师/教授') ;
insert into tb_det_user_career values(1008,'艺术工作者') ;
insert into tb_det_user_career values(1009,'企业销售人员') ;
insert into tb_det_user_career values(1010,'企业一般职员') ;
insert into tb_det_user_career values(1011,'企业初级/基层管理人员') ;
insert into tb_det_user_career values(1012,'企业中级管理人员') ;
insert into tb_det_user_career values(1013,'企业高级管理人员（如总经理/董事等）') ;
insert into tb_det_user_career values(1014,'私营企业业主') ;
insert into tb_det_user_career values(1015,'IT技术人员（程序员/网管）') ;
insert into tb_det_user_career values(1016,'国家机关工作人员/国家公务员') ;
insert into tb_det_user_career values(1017,'专业人士（如会计师/审计师/建筑师/律师等）') ;
insert into tb_det_user_career values(1018,'其他') ;

delete from tb_det_industry_class ;
insert into tb_det_industry_class values(1001,'计算机/互联网/通信/电子') ;
insert into tb_det_industry_class values(1002,'会计/金融/银行/保险') ;
insert into tb_det_industry_class values(1003,'贸易/消费/制造/营运') ;
insert into tb_det_industry_class values(1004,'制药/医疗') ;
insert into tb_det_industry_class values(1005,'广告/媒体') ;
insert into tb_det_industry_class values(1006,'房地产/建筑') ;
insert into tb_det_industry_class values(1007,'专业服务/教育/培训') ;
insert into tb_det_industry_class values(1008,'服务业') ;
insert into tb_det_industry_class values(1009,'物流/运输') ;
insert into tb_det_industry_class values(1010,'能源/原材料') ;
insert into tb_det_industry_class values(1011,'政府/非赢利机构/其他') ;

delete from tb_det_industry_class_sub ;
insert into tb_det_industry_class_sub values(100101,'计算机软件',1001,'计算机/互联网/通信/电子') ;
insert into tb_det_industry_class_sub values(100102,'计算机硬件',1001,'计算机/互联网/通信/电子') ;
insert into tb_det_industry_class_sub values(100103,'计算机服务(系统、数据服务、维修)',1001,'计算机/互联网/通信/电子') ;
insert into tb_det_industry_class_sub values(100104,'通信/电信/网络设备',1001,'计算机/互联网/通信/电子') ;
insert into tb_det_industry_class_sub values(100105,'通信/电信运营、增值服务',1001,'计算机/互联网/通信/电子') ;
insert into tb_det_industry_class_sub values(100106,'互联网/电子商务/网络游戏',1001,'计算机/互联网/通信/电子') ;
insert into tb_det_industry_class_sub values(100107,'电子技术/半导体/集成电路',1001,'计算机/互联网/通信/电子') ;
insert into tb_det_industry_class_sub values(100108,'仪器仪表/工业自动化',1001,'计算机/互联网/通信/电子') ;
insert into tb_det_industry_class_sub values(100201,'会计/审计',1002,'会计/金融/银行/保险') ;
insert into tb_det_industry_class_sub values(100202,'金融/投资/证券',1002,'会计/金融/银行/保险') ;
insert into tb_det_industry_class_sub values(100203,'银行',1002,'会计/金融/银行/保险') ;
insert into tb_det_industry_class_sub values(100204,'保险',1002,'会计/金融/银行/保险') ;
insert into tb_det_industry_class_sub values(100301,'贸易/进出口',1003,'贸易/消费/制造/营运') ;
insert into tb_det_industry_class_sub values(100302,'批发/零售',1003,'贸易/消费/制造/营运') ;
insert into tb_det_industry_class_sub values(100303,'快速消费品(食品、饮料、化妆品)',1003,'贸易/消费/制造/营运') ;
insert into tb_det_industry_class_sub values(100304,'服装/纺织/皮革',1003,'贸易/消费/制造/营运') ;
insert into tb_det_industry_class_sub values(100305,'家具/家电/工艺品/玩具/珠宝',1003,'贸易/消费/制造/营运') ;
insert into tb_det_industry_class_sub values(100306,'奢侈品/收藏品',1003,'贸易/消费/制造/营运') ;
insert into tb_det_industry_class_sub values(100307,'办公用品及设备',1003,'贸易/消费/制造/营运') ;
insert into tb_det_industry_class_sub values(100308,'机械/设备/重工',1003,'贸易/消费/制造/营运') ;
insert into tb_det_industry_class_sub values(100309,'汽车及零配件',1003,'贸易/消费/制造/营运') ;
insert into tb_det_industry_class_sub values(100401,'制药/生物工程',1004,'制药/医疗') ;
insert into tb_det_industry_class_sub values(100402,'医疗/护理/卫生',1004,'制药/医疗') ;
insert into tb_det_industry_class_sub values(100403,'医疗设备/器械',1004,'制药/医疗') ;
insert into tb_det_industry_class_sub values(100501,'广告',1005,'广告/媒体') ;
insert into tb_det_industry_class_sub values(100502,'公关/市场推广/会展',1005,'广告/媒体') ;
insert into tb_det_industry_class_sub values(100503,'影视/媒体/艺术/文化传播',1005,'广告/媒体') ;
insert into tb_det_industry_class_sub values(100504,'文字媒体/出版',1005,'广告/媒体') ;
insert into tb_det_industry_class_sub values(100505,'印刷/包装/造纸',1005,'广告/媒体') ;
insert into tb_det_industry_class_sub values(100601,'房地产开发',1006,'房地产/建筑') ;
insert into tb_det_industry_class_sub values(100602,'建筑/建材/工程',1006,'房地产/建筑') ;
insert into tb_det_industry_class_sub values(100603,'家居/室内设计/装潢',1006,'房地产/建筑') ;
insert into tb_det_industry_class_sub values(100604,'物业管理/商业中心',1006,'房地产/建筑') ;
insert into tb_det_industry_class_sub values(100701,'中介服务',1007,'专业服务/教育/培训') ;
insert into tb_det_industry_class_sub values(100702,'专业服务(咨询、人力资源、财会)',1007,'专业服务/教育/培训') ;
insert into tb_det_industry_class_sub values(100703,'外包服务',1007,'专业服务/教育/培训') ;
insert into tb_det_industry_class_sub values(100704,'检测，认证',1007,'专业服务/教育/培训') ;
insert into tb_det_industry_class_sub values(100705,'法律',1007,'专业服务/教育/培训') ;
insert into tb_det_industry_class_sub values(100706,'教育/培训/院校',1007,'专业服务/教育/培训') ;
insert into tb_det_industry_class_sub values(100707,'学术/科研',1007,'专业服务/教育/培训') ;
insert into tb_det_industry_class_sub values(100801,'餐饮业',1008,'服务业') ;
insert into tb_det_industry_class_sub values(100802,'酒店/旅游',1008,'服务业') ;
insert into tb_det_industry_class_sub values(100803,'娱乐/休闲/体育',1008,'服务业') ;
insert into tb_det_industry_class_sub values(100804,'美容/保健',1008,'服务业') ;
insert into tb_det_industry_class_sub values(100805,'生活服务',1008,'服务业') ;
insert into tb_det_industry_class_sub values(100901,'交通/运输/物流',1009,'物流/运输') ;
insert into tb_det_industry_class_sub values(100902,'航天/航空',1009,'物流/运输') ;
insert into tb_det_industry_class_sub values(101001,'石油/化工/矿产/地质',1010,'能源/原材料') ;
insert into tb_det_industry_class_sub values(101002,'采掘业/冶炼',1010,'能源/原材料') ;
insert into tb_det_industry_class_sub values(101003,'电力/水利',1010,'能源/原材料') ;
insert into tb_det_industry_class_sub values(101004,'新能源',1010,'能源/原材料') ;
insert into tb_det_industry_class_sub values(101005,'原材料和加工',1010,'能源/原材料') ;
insert into tb_det_industry_class_sub values(101101,'政府/公共事业',1011,'政府/非赢利机构/其他') ;
insert into tb_det_industry_class_sub values(101102,'非盈利机构',1011,'政府/非赢利机构/其他') ;
insert into tb_det_industry_class_sub values(101103,'环保',1011,'政府/非赢利机构/其他') ;
insert into tb_det_industry_class_sub values(101104,'农/林/牧/渔',1011,'政府/非赢利机构/其他') ;
insert into tb_det_industry_class_sub values(101105,'多元化业务集团公司',1011,'政府/非赢利机构/其他') ;
insert into tb_det_industry_class_sub values(101106,'其他行业',1011,'政府/非赢利机构/其他') ;

delete from tb_det_user_edu ;
insert into tb_det_user_edu values(1001,'小学') ;
insert into tb_det_user_edu values(1002,'初中') ;
insert into tb_det_user_edu values(1003,'高中') ;
insert into tb_det_user_edu values(1004,'专科') ;
insert into tb_det_user_edu values(1005,'本科') ;
insert into tb_det_user_edu values(1006,'硕士') ;
insert into tb_det_user_edu values(1007,'博士') ;
insert into tb_det_user_edu values(1008,'博士后') ;

delete from tb_det_user_income ;
insert into tb_det_user_income values(1,'2500元以下') ;
insert into tb_det_user_income values(2,'2500元-4999元') ;
insert into tb_det_user_income values(3,'5000元-9999元') ;
insert into tb_det_user_income values(4,'10000元-19999元') ;
insert into tb_det_user_income values(5,'20000元以上') ;

delete from tb_det_user_income_section ;
insert into tb_det_user_income_section values(1001,'1000元以下'   ,0   , 1000,  '2500元以下',     1) ;
insert into tb_det_user_income_section values(1002,'1000-1499元'  ,1000, 1499,  '2500元以下',     1) ;
insert into tb_det_user_income_section values(1003,'1500-1999元'  ,1500, 1999,  '2500元以下',     1) ;
insert into tb_det_user_income_section values(1004,'2000-2499元'  ,2000, 2499,  '2500元以下',     1) ;
insert into tb_det_user_income_section values(1005,'2500-2999元'  ,2500, 2999,  '2500元-4999元',  2) ;
insert into tb_det_user_income_section values(1006,'3000-3499元'  ,3000, 3499,  '2500元-4999元',  2) ;
insert into tb_det_user_income_section values(1007,'3500-3999元'  ,3500, 3999,  '2500元-4999元',  2) ;
insert into tb_det_user_income_section values(1008,'4000-4499元'  ,4000, 4499,  '2500元-4999元',  2) ;
insert into tb_det_user_income_section values(1009,'4500-4999元'  ,4500, 4999,  '2500元-4999元',  2) ;
insert into tb_det_user_income_section values(1010,'5000-5499元'  ,5000, 5499,  '5000元-9999元',  3) ;
insert into tb_det_user_income_section values(1011,'5500-5000元'  ,5500, 5000,  '5000元-9999元',  3) ;
insert into tb_det_user_income_section values(1012,'6000-6999元'  ,6000, 6999,  '5000元-9999元',  3) ;
insert into tb_det_user_income_section values(1013,'7000-7999元'  ,7000, 7999,  '5000元-9999元',  3) ;
insert into tb_det_user_income_section values(1014,'8000-9999元'  ,8000, 9999,  '5000元-9999元',  3) ;
insert into tb_det_user_income_section values(1015,'10000-11999元',10000,11999, '10000元-19999元',4) ;
insert into tb_det_user_income_section values(1016,'12000-13999元',12000,13999, '10000元-19999元',4) ;
insert into tb_det_user_income_section values(1017,'14000-15999元',14000,15999, '10000元-19999元',4) ;
insert into tb_det_user_income_section values(1018,'16000-17999元',16000,17999, '10000元-19999元',4) ;
insert into tb_det_user_income_section values(1019,'18000-19999元',18000,19999, '10000元-19999元',4) ;
insert into tb_det_user_income_section values(1020,'20000-24999元',20000,24999, '20000元以上',    5) ;
insert into tb_det_user_income_section values(1021,'25000-29999元',25000,29999, '20000元以上',    5) ;
insert into tb_det_user_income_section values(1022,'30000-39999元',30000,39999, '20000元以上',    5) ;
insert into tb_det_user_income_section values(1023,'40000-49999元',40000,49999, '20000元以上',    5) ;
insert into tb_det_user_income_section values(1024,'50000元以上'  ,50000,999999,'20000元以上',    5) ;

insert into tb_det_user_age values(1001,'15岁及以下',0, 15) ;
insert into tb_det_user_age values(1002,'16岁-24岁', 16,24) ;
insert into tb_det_user_age values(1003,'25岁-34岁', 25,34) ;
insert into tb_det_user_age values(1004,'35岁-44岁', 35,44) ;
insert into tb_det_user_age values(1005,'45岁-54岁', 45,54) ;
insert into tb_det_user_age values(1006,'55岁-64岁', 55,64) ;
insert into tb_det_user_age values(1007,'65岁及以上',65,99) ;

delete from tb_det_user_character ;
insert into tb_det_user_character values(1001,'温柔') ;
insert into tb_det_user_character values(1002,'粗狂') ;
insert into tb_det_user_character values(1003,'活泼') ;
insert into tb_det_user_character values(1004,'老成') ;
insert into tb_det_user_character values(1005,'内向') ;
insert into tb_det_user_character values(1006,'开朗') ;
insert into tb_det_user_character values(1007,'好爽') ;
insert into tb_det_user_character values(1008,'稳重') ;

delete from tb_det_user_affection ;
insert into tb_det_user_affection values(1001,'单身中') ;
insert into tb_det_user_affection values(1002,'恋爱中') ;
insert into tb_det_user_affection values(1003,'已结婚') ;

delete from tb_det_user_stature ;
insert into tb_det_user_stature values(1001,'苗条') ;
insert into tb_det_user_stature values(1002,'丰满') ;
insert into tb_det_user_stature values(1003,'中等') ;
insert into tb_det_user_stature values(1004,'高大') ;
insert into tb_det_user_stature values(1005,'小巧') ;
insert into tb_det_user_stature values(1006,'运动') ;
insert into tb_det_user_stature values(1007,'健美') ;

delete from tb_det_user_hobby ;
insert into tb_det_user_hobby values(1001,'音乐') ;
insert into tb_det_user_hobby values(1002,'影视') ;
insert into tb_det_user_hobby values(1003,'运动') ;
insert into tb_det_user_hobby values(1004,'游戏') ;
insert into tb_det_user_hobby values(1005,'数码') ;
insert into tb_det_user_hobby values(1006,'美食') ;
insert into tb_det_user_hobby values(1007,'旅游') ;
insert into tb_det_user_hobby values(1008,'读书') ;

delete from tb_det_survey_type ;
insert into tb_det_survey_type values(1001,'民意调查','民意调查描述') ;
insert into tb_det_survey_type values(1002,'商业调查','商业调查描述') ;
insert into tb_det_survey_type values(1003,'品牌调查','品牌调查描述') ;
insert into tb_det_survey_type values(1004,'个性调查','个性调查描述') ;

delete from tb_det_survey_type_sub ;
insert into tb_det_survey_type_sub values(1001,'民意调查',10001,'公益',0) ;
insert into tb_det_survey_type_sub values(1001,'民意调查',10002,'环保',0) ;
insert into tb_det_survey_type_sub values(1001,'民意调查',10003,'时政',0) ;
insert into tb_det_survey_type_sub values(1001,'民意调查',10004,'社情',0) ;
insert into tb_det_survey_type_sub values(1001,'民意调查',10005,'财经',0) ;
insert into tb_det_survey_type_sub values(1001,'民意调查',10006,'文教',0) ;
insert into tb_det_survey_type_sub values(1002,'商业调查',10007,'市场调研',0) ;
insert into tb_det_survey_type_sub values(1002,'商业调查',10008,'产品反馈',0) ;
insert into tb_det_survey_type_sub values(1002,'商业调查',10009,'客户服务',0) ;
insert into tb_det_survey_type_sub values(1002,'商业调查',10010,'企业管理',0) ;
insert into tb_det_survey_type_sub values(1003,'品牌调查',10011,'品牌排行',0) ;
insert into tb_det_survey_type_sub values(1003,'品牌调查',10012,'品牌满意度',0) ;
insert into tb_det_survey_type_sub values(1003,'品牌调查',10013,'品牌关注度',0) ;
insert into tb_det_survey_type_sub values(1004,'个性调查',10014,'娱乐',0) ;
insert into tb_det_survey_type_sub values(1004,'个性调查',10015,'情感',0) ;
insert into tb_det_survey_type_sub values(1004,'个性调查',10016,'校园',0) ;
insert into tb_det_survey_type_sub values(1004,'个性调查',10017,'职场',0) ;
insert into tb_det_survey_type_sub values(1004,'个性调查',10018,'话题',0) ;

delete from tb_det_survey_class ;
insert into tb_det_survey_class values(1001,'机构组织') ;
insert into tb_det_survey_class values(1002,'农林牧渔') ;
insert into tb_det_survey_class values(1003,'医药卫生') ;
insert into tb_det_survey_class values(1004,'建筑建材') ;
insert into tb_det_survey_class values(1005,'冶金矿产') ;
insert into tb_det_survey_class values(1006,'石油化工') ;
insert into tb_det_survey_class values(1007,'水利水电') ;
insert into tb_det_survey_class values(1008,'交通运输') ;
insert into tb_det_survey_class values(1009,'信息产业') ;
insert into tb_det_survey_class values(1010,'机械机电') ;
insert into tb_det_survey_class values(1011,'轻工食品') ;
insert into tb_det_survey_class values(1012,'服装纺织') ;
insert into tb_det_survey_class values(1013,'专业服务') ;
insert into tb_det_survey_class values(1014,'安全防护') ;
insert into tb_det_survey_class values(1015,'环保绿化') ;
insert into tb_det_survey_class values(1016,'旅游休闲') ;
insert into tb_det_survey_class values(1017,'办公文教') ;
insert into tb_det_survey_class values(1018,'电子电工') ;
insert into tb_det_survey_class values(1019,'玩具礼品') ;
insert into tb_det_survey_class values(1020,'家居用品') ;
insert into tb_det_survey_class values(1021,'物资专材') ;
insert into tb_det_survey_class values(1022,'包装用品') ;
insert into tb_det_survey_class values(1023,'体育用品') ;
insert into tb_det_survey_class values(1024,'办公家具') ;

delete from tb_det_survey_state ;
insert into tb_det_survey_state values(0,'无效问卷','无效') ;
insert into tb_det_survey_state values(1,'创建草稿','草稿') ;
insert into tb_det_survey_state values(2,'问卷发布','已发布') ;
insert into tb_det_survey_state values(3,'活动开始','进行中') ;
insert into tb_det_survey_state values(4,'活动结束','已结束') ;

delete from tb_det_survey_recomm_type ;
insert into tb_det_survey_recomm_type values(0,'不推荐') ;
insert into tb_det_survey_recomm_type values(1,'用户自定义推荐') ;
insert into tb_det_survey_recomm_type values(2,'系统自动推荐') ;

delete from tb_det_question_class ;
insert into tb_det_question_class values('10001','3C数码') ;
insert into tb_det_question_class values('10002','服饰鞋包') ;
insert into tb_det_question_class values('10003','家用电器') ;
insert into tb_det_question_class values('10004','家装家具') ;
insert into tb_det_question_class values('10005','母婴用品') ;
insert into tb_det_question_class values('10006','生活服务') ;
insert into tb_det_question_class values('10007','食品保健品') ;
insert into tb_det_question_class values('10008','虚拟业务') ;
insert into tb_det_question_class values('10009','文化娱乐') ;
insert into tb_det_question_class values('10010','运动户外') ;
insert into tb_det_question_class values('10011','珠宝首饰') ;
insert into tb_det_question_class values('10012','其他业务') ;

delete from tb_det_question_prop ;
insert into tb_det_question_prop values('1','单选题') ;
insert into tb_det_question_prop values('2','多选题') ;
insert into tb_det_question_prop values('3','主观题') ;

delete from tb_det_reward_type ;
insert into tb_det_reward_type values('10','无奖励') ;
insert into tb_det_reward_type values('11','减免邮费') ;
insert into tb_det_reward_type values('12','赠送优惠券') ;
insert into tb_det_reward_type values('13','赠送礼品') ;
insert into tb_det_reward_type values('14','积分抽奖') ;

delete from tb_det_recommend_user_state ;
insert into tb_det_recommend_user_state values(0,'失效') ;
insert into tb_det_recommend_user_state values(1,'用户生成') ;
insert into tb_det_recommend_user_state values(2,'已推荐') ;
insert into tb_det_recommend_user_state values(3,'已参与') ;

delete from tb_det_survey_recommend_state ;
insert into tb_det_survey_recommend_state values(0,'失效规则') ;
insert into tb_det_survey_recommend_state values(1,'临时规则') ;
insert into tb_det_survey_recommend_state values(2,'有效规则') ;

delete from tb_det_survey_recommend_type ;
insert into tb_det_survey_recommend_type values(0,'不推荐') ;
insert into tb_det_survey_recommend_type values(1,'系统推荐') ;
insert into tb_det_survey_recommend_type values(2,'自定义推荐') ;

delete from tb_det_question_type ;
insert into tb_det_question_type values('radio','单选题') ;
insert into tb_det_question_type values('checkbox','多选题') ;
insert into tb_det_question_type values('textarea','主观题') ;

delete from tb_det_user_level ;
insert into tb_det_user_level values(0,'新手',-1,-1) ;
insert into tb_det_user_level values(1,'九品',0,99) ;
insert into tb_det_user_level values(2,'八品',100,299) ;
insert into tb_det_user_level values(3,'七品',300,599) ;
insert into tb_det_user_level values(4,'六品',600,999) ;
insert into tb_det_user_level values(5,'五品',1000,1499) ;
insert into tb_det_user_level values(6,'四品',1500,1999) ;
insert into tb_det_user_level values(7,'三品',2000,2999) ;
insert into tb_det_user_level values(8,'二品',3000,3999) ;
insert into tb_det_user_level values(9,'一品',4000,4999) ;
insert into tb_det_user_level values(10,'一段',5000,6499) ;
insert into tb_det_user_level values(11,'二段',6500,7999) ;
insert into tb_det_user_level values(12,'三段',8000,9999) ;
insert into tb_det_user_level values(13,'四段',10000,11999) ;

delete from tb_det_user_level_right ;
insert into tb_det_user_level_right values(-1,'不允许任何用户' ) ;
insert into tb_det_user_level_right values(0,'允许新手等级以上用户' ) ;
insert into tb_det_user_level_right values(1,'允许九品等级以上用户' ) ;
insert into tb_det_user_level_right values(2,'允许八品等级以上用户' ) ;
insert into tb_det_user_level_right values(3,'允许七品等级以上用户' ) ;
insert into tb_det_user_level_right values(4,'六品等级以上用户' ) ;
insert into tb_det_user_level_right values(5,'允许五品等级以上用户' ) ;
insert into tb_det_user_level_right values(6,'允许四品等级以上用户' ) ;
insert into tb_det_user_level_right values(7,'允许三品等级以上用户' ) ;
insert into tb_det_user_level_right values(8,'允许二品等级以上用户' ) ;
insert into tb_det_user_level_right values(9,'允许一品等级以上用户' ) ;
insert into tb_det_user_level_right values(10,'允许一段等级以上用户') ;
insert into tb_det_user_level_right values(11,'允许二段等级以上用户') ;
insert into tb_det_user_level_right values(12,'允许三段等级以上用户') ;
insert into tb_det_user_level_right values(13,'允许四段等级以上用户') ;
insert into tb_det_user_level_right values(999,'允许所有用户') ;

delete from tb_det_score_add_rule ;
insert into tb_det_score_add_rule values(1001,'参与调查活动',1,1) ;
insert into tb_det_score_add_rule values(1002,'发布调查活动',1,5) ;
insert into tb_det_score_add_rule values(1003,'完成日常任务',1,10) ;

delete from tb_det_coins_action_rule ;
insert into tb_det_coins_action_rule values(1001,'创建调查活动',1,-1,50) ;
insert into tb_det_coins_action_rule values(1002,'创建调查问题',1,-1,10) ;
insert into tb_det_coins_action_rule values(1003,'完成新手任务',2,1,100) ;

delete from tb_det_user_action_type ;
insert into tb_det_user_action_type values(0,'失效活动') ;
insert into tb_det_user_action_type values(1,'循环性活动') ;
insert into tb_det_user_action_type values(2,'一次性活动') ;

delete from tb_det_user_action_config ;
insert into tb_det_user_action_config values(1001,'参与问卷调查活动',1,'BasSurveyInfo'  ,'survey_code'  ,'survey_name'  ,1,1,1,null,1) ;
insert into tb_det_user_action_config values(1002,'发布问卷调查活动',1,'BasSurveyInfo'  ,'survey_code'  ,'survey_name'  ,1,5,-1,null,1) ;
insert into tb_det_user_action_config values(1003,'创建问卷'        ,1,'BasSurveyInfo'  ,'survey_code'  ,'survey_name'  ,0,0,-1,50,0) ;
insert into tb_det_user_action_config values(1004,'创建问卷调查问题',1,'BasQuestionInfo','question_code','question_name',0,0,-1,10,0) ;
insert into tb_det_user_action_config values(1005,'主动推荐调查活动',1,'BasSurveyInfo'  ,'survey_code'  ,'survey_name'  ,0,0,-1,30,0) ;
insert into tb_det_user_action_config values(2001,'完成新手任务'    ,2,null,null,'新手任务',1,10,0,0,1) ;

delete from tb_det_user_action_config ;
insert into tb_det_user_action_config values(1001,'参与调查活动',1,1, 1,null,'user_coins',   'BasSurveyInfo',  'survey_code','survey_name','answer_coins',1) ;
insert into tb_det_user_action_config values(1001,'参与调查活动',1,1, 1,   1,'user_score',   'BasSurveyInfo',  'survey_code','survey_name',          null,1) ;
insert into tb_det_user_action_config values(1001,'参与调查活动',1,1, 1,   1,'answer_times', 'BasSurveyInfo',  'survey_code','survey_name',          null,0) ;
insert into tb_det_user_action_config values(1002,'发布调查活动',1,1,-1,null,'user_coins',   'BasSurveyInfo',  'survey_code','survey_name','create_coins',1) ;
insert into tb_det_user_action_config values(1002,'发布调查活动',1,1, 1,   5,'user_score',   'BasSurveyInfo',  'survey_code','survey_name',          null,1) ;
insert into tb_det_user_action_config values(1002,'发布调查活动',1,1, 1,   1,'publish_times','BasSurveyInfo',  'survey_code','survey_name',          null,0) ;
insert into tb_det_user_action_config values(1003,'创建调查活动',1,1,-1,  50,'user_coins',   'BasSurveyInfo',  'survey_code','survey_name',          null,0) ;
insert into tb_det_user_action_config values(1004,'创建调查题目',1,1,-1,  10,'user_coins', 'BasQuestionInfo','question_code','question_name',        null,0) ;
insert into tb_det_user_action_config values(1005,'主动推荐调查',1,1,-1,  30,'user_coins',   'BasSurveyInfo',  'survey_code','survey_name',          null,0) ;
insert into tb_det_user_action_config values(2001,'完成新手任务',1,2, 1,  10,'user_score',              null,           null,   '新手任务',          null,1) ;

delete from tb_det_user_type_survey_recomm_relation ;
insert into tb_det_user_type_survey_recomm_relation values(1,1,'官方发布的调查') ;
insert into tb_det_user_type_survey_recomm_relation values(2,2,'付费调查或付费用户发布的调查') ;
insert into tb_det_user_type_survey_recomm_relation values(3,3,'认证用户发布调查') ;
insert into tb_det_user_type_survey_recomm_relation values(4,4,'高级用户发布的调查') ;
insert into tb_det_user_type_survey_recomm_relation values(5,5,'普通用户发布的调查') ;



